os = "RoDOS"
version = "0.1.0"
author = "Sami Barbut-Dica"
cluster_size = 16
cluster_count = 4096
storage_file_path = "storage.bin"

[prompt]
host = "rodos"
separator = "@"
user = "rouser"
path_prefix = ":"
terminator = "$"

[commands]
    [commands.neofetch]
    name = "neofetch"
    description = "Display system information"
    usage = "neofetch"
    regex = "\\s*neofetch\\s*"

    [commands.create]
    name = "create"
    description = "Create a new file"
    usage = "create <file_name>.<file_extension> <file_size> <file_content_type>"
    regex = "\\s*create\\s+(?P<name>\\S+)\\.(?P<extension>\\S+)\\s+(?P<dim>\\S+)\\s+(?P<type>\\S+)\\s*"

    [commands.ls]
    name = "ls"
    description = "List files"
    usage = "ls"
    regex = "\\s*ls\\s*"
