os = "RoDOS"
version = "0.1.0"
author = "Sami Barbut-Dica"
storage_file_path = "disk/storage.bin"

[prompt]
host = "rodos"
separator = "@"
user = "rouser"
path_prefix = ":"
terminator = "$"

[commands]
    [commands.help]
    name = "help"
    description = "Display the list of available commands"
    usage = "help"
    regex = "^\\s*help\\s*$"

    [commands.exit]
    name = "exit"
    description = "Exit the shell"
    usage = "exit"
    regex = "^\\s*exit\\s*$"

    [commands.neofetch]
    name = "neofetch"
    description = "Display system information"
    usage = "neofetch"
    regex = "^\\s*neofetch\\s*$"

    [commands.create]
    name = "create"
    description = "Create a new file"
    usage = "create <file_name>.<file_extension> <file_size> <file_content_type>"
    regex = "^\\s*create\\s+(?P<name>\\S+)\\.(?P<extension>\\S+)\\s+(?P<dim>\\d+)\\s+(?P<type>\\S+)\\s*$"

    [commands.ls]
    name = "ls"
    description = "List files and directories from the current directory"
    usage = "ls"
    regex = "^\\s*ls\\s*$"

    [commands.rename]
    name = "rename"
    description = "Rename a file or a directory"
    usage = "rename <old_name> <new_name>"
    regex = "^\\s*rename\\s+(?P<old_name>\\S+)\\.(?P<old_extension>\\S+)\\s+(?P<new_name>\\S+)\\.(?P<new_extension>\\S+)\\s*$"

    [commands.del]
    name = "del"
    description = "Delete a file or a directory"
    usage = "del <file_name>.<file_extension>"
    regex = "^\\s*del\\s+(?P<name>\\S+)\\.(?P<extension>\\S+)\\s*$"

    [commands.cat]
    name = "cat"
    description = "Display the content of a file"
    usage = "cat <file_name>.<file_extension>"
    regex = "^\\s*cat\\s+(?P<name>\\S+)\\.(?P<extension>\\S+)\\s*$"

    [commands.cp]
    name = "cp"
    description = "Copy a file"
    usage = "cp <file_name>.<file_extension> <new_file_name>.<new_file_extension>"
    regex = "^\\s*cp\\s+(?P<src_name>\\S+)\\.(?P<src_extension>\\S+)\\s+(?P<dest_name>\\S+)\\.(?P<dest_extension>\\S+)\\s*$"
