os = "RoDOS"
version = "0.1.0"
author = "Sami Barbut-Dica"
disk_dir_path = "disk"
storage_file_path = "disk/storage.bin"
stdin_file_path = "disk/stdin.in"
temp_file_path = "disk/temp"

[prompt]
host = "rodos"
separator = "@"
user = "rouser"
path_prefix = ":"
terminator = "$"

[commands]
    [commands.help]
    name = "help"
    description = "Display the list of available commands"
    usage = "help [command]"
    regex = "^\\s*help(\\s+(?P<command>\\S+))?\\s*$"

    [commands.exit]
    name = "exit"
    description = "Exit the shell"
    usage = "exit"
    regex = "^\\s*exit\\s*$"

    [commands.neofetch]
    name = "neofetch"
    description = "Display system information"
    usage = "neofetch"
    regex = "^\\s*neofetch\\s*$"

    [commands.create]
    name = "create"
    description = "Create a new file"
    usage = "create <file_name>.<file_extension> <file_size> -<file_content_type>"
    regex = "^\\s*create\\s+(?P<name>\\S+)\\.(?P<extension>\\S+)\\s+(?P<dim>\\d+)\\s+-(?P<type>\\S+)\\s*$"

    [commands.ls]
    name = "ls"
    description = "List files and directories from the current directory by applying given filters and sorting options"
    usage = "ls [-<filter>] [-name=<file_name>] [-ext=<file_extension>] [-<sort>]\n-<filter>:\n\t-a: show all visible files and directories\n\t-h: show all files and directories including hidden ones\n\t-s: show files and directories in short format (name and extension)\n\t-l: show files and directories in detailed format (attributes, name, extension, last modification date and size in bytes)\n\t-f: show all files\n\t-d: show all directories\n-<sort>:\n\t-n: sort by name\n\t-t: sort by last modification date\n\t-sz: sort by size\n\t-*a: sort in ascending order\n\t-*d: sort in descending order"
    regex = "^\\s*ls(\\s+-(?P<filter_basic>(a|h)(s|l)?(f|d)?))?(\\s+-name=(?P<filter_name>\\S+))?(\\s+-ext=(?P<filter_extension>\\S+))?(\\s+-(?P<sort>(n|t|sz)(a|d)))?\\s*$"

    [commands.rename]
    name = "rename"
    description = "Rename a file or a directory"
    usage = "rename <old_name> <new_name>"
    regex = "^\\s*rename\\s+(?P<old_name>[a-zA-Z0-9_]+)(\\.(?P<old_extension>\\S+))?\\s+(?P<new_name>[a-zA-Z0-9_]+)(\\.(?P<new_extension>\\S+))?\\s*$"

    [commands.del]
    name = "del"
    description = "Delete a file or a directory"
    usage = "del <file_name>.<file_extension> or del <directory_name>"
    regex = "^\\s*del\\s+(?P<name>[a-zA-Z0-9_]+)(\\.(?P<extension>\\S+))?\\s*$"

    [commands.cat]
    name = "cat"
    description = "Display the content of a file"
    usage = "cat <file_name>.<file_extension>"
    regex = "^\\s*cat\\s+(?P<name>\\S+)\\.(?P<extension>\\S+)\\s*$"

    [commands.cp]
    name = "cp"
    description = "Copy a file"
    usage = "cp <file_name>.<file_extension> <new_file_name>.<new_file_extension>"
    regex = "^\\s*cp\\s+(?P<src_name>\\S+)\\.(?P<src_extension>\\S+)\\s+(?P<dest_name>\\S+)\\.(?P<dest_extension>\\S+)\\s*$"

    [commands.fmt]
    name = "fmt"
    description = "Format the disk using the specified FAT cluster size and reboot the system"
    usage = "fmt 16/32"
    regex = "^\\s*fmt\\s+(?P<fat_type>(16|32))\\s*$"

    [commands.defrag]
    name = "defrag"
    description = "Defragment the disk"
    usage = "defrag"
    regex = "^\\s*defrag\\s*$"

    [commands.setattr]
    name = "setattr"
    description = "Set the attributes of a file or a directory"
    usage = "setattr <file_name>.<file_extension> <attributes>(max 2 blocks, e.g. +w-h, but not +w-h+h)\n<attributes>:\n\t+w: make read-write\n\t-w: make read-only\n\t+h: make hidden\n\t-h: make visible"
    regex = "^\\s*setattr\\s+(?P<name>[a-zA-Z0-9_]+)(\\.(?P<extension>\\S+))?\\s+(?P<attributes>((\\+|-)(w|h)){1,2})\\s*$"

    [commands.mkdir]
    name = "mkdir"
    description = "Create a new directory"
    usage = "mkdir <directory_name>"
    regex = "^\\s*mkdir\\s+(?P<name>\\S+)\\s*$"

    [commands.cd]
    name = "cd"
    description = "Change the current directory"
    usage = "cd <directory_name>"
    regex = "^\\s*cd\\s+(?P<name>\\S+)\\s*$"

    [commands.pwd]
    name = "pwd"
    description = "Display the current directory"
    usage = "pwd"
    regex = "^\\s*pwd\\s*$"
